/// Generated by st_config_check.dart according to st_config.dart
class STConfigGlobal {
  // File components
  static String fileImageResize = "Image Resize";
  static String fileImageFormat = "Image Format";

  // Convert components
  static String convertEncodeDecode = "Encode/Decode";

  // Other components
  static String otherColorPicker = "Color Picker";
}
